POSTGRES_HOST=judge0-db
POSTGRES_DB=judge0
POSTGRES_USER=judge0
POSTGRES_PASSWORD=judge0pass

REDIS_HOST=judge0-redis

# отключаем телеметрию
JUDGE0_TELEMETRY_ENABLE=false
DISABLE_ISOLATE_SANDBOX=true