# Generated by Django 4.2.29 on 2026-03-28 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0001_initial'),
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('language', models.CharField(choices=[('python', 'Python')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'ожидание'), ('running', 'запущен'), ('accepted', 'принят'), ('wrong_answer', 'неправильный ответ'), ('time_limit', 'превышен лимит времени'), ('memory_limit', 'превышен лимит памяти'), ('runtime_error', 'ошибка времени выполнения'), ('compilation_error', 'ошибка компиляции')], default='pending', max_length=50)),
                ('runtime_ms', models.IntegerField(null=True)),
                ('memory_mb', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.contest')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='problems.problem')),
            ],
        ),
    ]
