# Generated by Django 4.2.29 on 2026-03-15 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_initial'),
        ('submissions', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='push_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='task',
            new_name='problem',
        ),
        migrations.AlterField(
            model_name='submission',
            name='contest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.contest'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('pending', 'ожидание'), ('running', 'запущен'), ('accepted', 'принят'), ('wrong_answer', 'неправильный ответ'), ('time_limit', 'превышен лимит времени'), ('memory_limit', 'превышен лимит памяти'), ('runtime_error', 'ошибка времени выполнения'), ('compilation_error', 'ошибка компиляции')], default='pending', max_length=50),
        ),
    ]
