# Generated by Django 4.2.29 on 2026-03-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_initial'),
        ('contests', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='problems',
            field=models.ManyToManyField(related_name='contest', to='problems.problem'),
        ),
    ]
