# Generated by Django 4.2.29 on 2026-03-30 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_alter_contest_problems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='status',
        ),
    ]
